// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX7pTZ4kv2dlcYWGaOFbIykSPkS1NqsQ8',
    appId: '1:853877328506:web:75e5b7b3091587e3cc09c3',
    messagingSenderId: '853877328506',
    projectId: 'weatherapp-1ee2a',
    authDomain: 'weatherapp-1ee2a.firebaseapp.com',
    storageBucket: 'weatherapp-1ee2a.appspot.com',
    measurementId: 'G-7CGDK3S326',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhweaNgn9FE4Jimz7jVx4TPXnEGiHOuU8',
    appId: '1:853877328506:android:f5d9b38556872250cc09c3',
    messagingSenderId: '853877328506',
    projectId: 'weatherapp-1ee2a',
    storageBucket: 'weatherapp-1ee2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3VG3aO521zT9EZLypoRP0R_Gu52b2dQ',
    appId: '1:853877328506:ios:03a055313909d72acc09c3',
    messagingSenderId: '853877328506',
    projectId: 'weatherapp-1ee2a',
    storageBucket: 'weatherapp-1ee2a.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ3VG3aO521zT9EZLypoRP0R_Gu52b2dQ',
    appId: '1:853877328506:ios:03a055313909d72acc09c3',
    messagingSenderId: '853877328506',
    projectId: 'weatherapp-1ee2a',
    storageBucket: 'weatherapp-1ee2a.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX7pTZ4kv2dlcYWGaOFbIykSPkS1NqsQ8',
    appId: '1:853877328506:web:20d9c08d7cd38ef1cc09c3',
    messagingSenderId: '853877328506',
    projectId: 'weatherapp-1ee2a',
    authDomain: 'weatherapp-1ee2a.firebaseapp.com',
    storageBucket: 'weatherapp-1ee2a.appspot.com',
    measurementId: 'G-V3CLYRCWH7',
  );
}
